name: Compile snapshot with Maven

on:
  push:
    branches-ignore:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19.0.2+7'
          distribution: 'adopt'
      - name: Deploy snapshot with Maven
        env:
          MVN_REPO_USER: ${{ secrets.MVN_REPO_USER }}
          MVN_REPO_PASS: ${{ secrets.MVN_REPO_PASS }}
          ANDEV_RES_ID: 1
        run: |
          sudo apt install jq -y
          curl -X GET https://api.andrei1058.dev/v1/resources/$ANDEV_RES_ID/versioning/current -H "Accept: application/json" >> version.json
          export UPDATE_VERSION=`jq '.version' version.json | tr -d '"'`
          mvn versions:set -DnewVersion=$UPDATE_VERSION-SNAPSHOT
          mvn versions:update-child-modules
          mvn clean install -s ci_settings.xml
          echo "UPDATE_VERSION=$UPDATE_VERSION" >> $GITHUB_ENV
      
      - name: List files
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R
          echo "Find .jar files:"
          find . -name "*.jar"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bedwars1058-${{ env.UPDATE_VERSION }}-SNAPSHOT
          path: |
            **/target/*.jar
            ** /*.jar
